// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef ics213_dialog_h
#define ics213_dialog_h
#include <FL/Fl.H>
#include <FL/Fl_Pixmap.H>
#include <FL/Fl_Text_Editor.H>
#include "FTextView.h"
#include "flinput2.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include "ics213.h"
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
extern Fl_Input2 *txt_To;
extern Fl_Input2 *txt_P1;
extern Fl_Input2 *txt_Fm;
extern Fl_Input2 *txt_P2;
extern Fl_Input2 *txt_Subj;
#include "calendar.h"
extern Fl_DateInput *txt_D1;
#include <FL/Fl_Button.H>
extern Fl_Button *btnDate1;
extern Fl_Input2 *txt_T1;
extern Fl_Button *btnTime1;
extern FTextEdit *txt_Msg;
extern Fl_Input2 *txt_S1;
extern Fl_Input2 *txt_P3;
extern Fl_Input2 *txt_S2;
extern Fl_DateInput *txt_D2;
extern Fl_Input2 *txt_T2;
extern Fl_Button *btnTime2;
extern FTextEdit *txt_Reply;
extern Fl_Input2 *txt_P4;
extern Fl_Button *btnDate2;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *btnUTC;
#include <FL/Fl_Output.H>
extern Fl_Output *txt_filename;
Fl_Double_Window* ics_dialog();
extern Fl_Menu_Item menu_[];
#define mnuNew (menu_+1)
#define mnuOpen (menu_+2)
#define mnuSave (menu_+3)
#define mnuSaveAs (menu_+4)
#define mnuWrite (menu_+5)
#define mnu_qimport (menu_+7)
#define mnu_qexport (menu_+8)
#define mnuWrapImport (menu_+11)
#define mnuWrapExport (menu_+12)
#define mnuAutoSend (menu_+13)
#define mnuExit (menu_+15)
#define mnu_load_template (menu_+18)
#define mnu_save_template (menu_+19)
#define mnu_save_as_template (menu_+20)
#define mnuOptions (menu_+24)
#define mnuAbout (menu_+25)
#include <FL/Fl_Browser.H>
extern Fl_Browser *brwsOptions;
#include <FL/Fl_Return_Button.H>
extern Fl_Return_Button *btnCloseOptions;
#include <FL/Fl_Box.H>
Fl_Double_Window* optionsdialog();
#endif
